import AppKit

@MainActor
final class ClipboardMonitor: ObservableObject {
    @Published var isPaused = false

    private let store: HistoryStore
    private var timer: Timer?
    private var lastChangeCount: Int
    private var ignoredChangeCount: Int?

    /// Types password managers (and other privacy-aware apps) attach to payloads
    /// that must never be recorded. See http://nspasteboard.org
    static let privacyMarkerTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    init(store: HistoryStore) {
        self.store = store
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Writes an item back to the clipboard, marking the resulting change so the
    /// next poll doesn't re-record it as a duplicate.
    func copyBack(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        ignoredChangeCount = pasteboard.changeCount
    }

    func poll() {
        let pasteboard = NSPasteboard.general
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        if count == ignoredChangeCount {
            ignoredChangeCount = nil
            return
        }
        guard !isPaused else { return }
        guard !Self.isPrivacyMarked(pasteboard) else { return }
        guard let text = pasteboard.string(forType: .string) else { return }
        store.add(text)
    }

    static func isPrivacyMarked(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return privacyMarkerTypes.contains(where: types.contains)
    }
}
